<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/custom.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')


        ;
        ?>

    </head>
    <body class="body"> 
        <header class="mainHeader">
            <div class='logo'>
                <div class="social">
                    <p class="follow"><b>Follow Us</b></p>
                    <a href="https://twitter.com/@homesteadpsc"><img src='../images/icons/twitter.png'/></a>
                    <a href="https://www.facebook.com/TheHomesteadProjectStreetChildren?fref=ts"><img src='../images/icons/facebook_2.png'/></a>
                    <br/><br/>
                    <p id="login"><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a> |
                        <a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a> </p>  
                </div>
                <img src="../images/logo3.png" class="logo-1"/>
            </div>
            <div class= "navbar navbar-default">
                <div class= "container">
                    <div class ="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class ="icon-bar"></span>
                            <span class ="icon-bar"></span>
                            <span class ="icon-bar"></span>
                            <span class ="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav  navbar-nav">
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('about/legal') ?>">Legal, NPO, PBO Status</a></li>
                                    <li><a href="http://issuu.com/paulvernonhooper/docs/the_homestead__projects_for_street_/1" target="_blank">Audited Financials  2014  </a></li>
                                    <li><a href="http://issuu.com/paulvernonhooper/docs/homestead_2014_final_low_res/1" target="_blank">Annual Report 2014</a></li>
                                    <li><a href="<?php echo $this->url('about/business') ?>">Business Canvas</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Gallery <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('gallery/photos') ?>">Photos</a></li>
                                    <li><a href="<?php echo $this->url('gallery/videos') ?>">Videos</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Donate <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('donate/myschool') ?>">My School</a></li>
                                    <li><a href="<?php echo $this->url('donate/youdonate') ?>">You Donate</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('volunteering') ?>"><?php echo $this->translate('Volunteering') ?></a></li>

                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Our Projects <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('projects/intake') ?>">Intake Shelter</a></li>
                                    <li><a href="<?php echo $this->url('projects/children') ?>">Children Home</a></li>
                                    <li><a href="<?php echo $this->url('projects/outreach') ?>">Outreach Work</a></li>
                                    <li><a href="<?php echo $this->url('projects/prevention') ?>">Prevention and Early Intervention</a></li>

                                </ul>
                            </li>

                            <li class="active"><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact') ?></a></li>
                        </ul> 

                    </div>

                </div>
                <div class='c'></div>
            </div>

        </header>
        <div class='c'></div>
        <div class="reg-wrapper">
            <br>
            <?php
            $form = $this->form;
//$form->setAttribute('action', $this->url('register/default', array('controller' => 'registration', 'action' => 'index')));

            $form->prepare();
            $form->get('email')->setAttributes(array(
                'class' => 'form-control',
            ));

            $form->get('subject')->setAttributes(array(
                'class' => 'form-control',
            ));

            $form->get('body')->setAttributes(array(
                'class' => 'form-control',
            ));

            $form->get('csrf')->setAttributes(array(
                'class' => 'form-control',
                'placeholder' => 'confirm password'
            ));

            $form->get('captcha')->setAttributes(array(
                'class' => 'form-control',
            ));
            $form->get('submit')->setAttributes(array('class' => 'btn btn-primary'));
            ?>
            <div class='reg'>
                <div class="clear"></div>                 
                <h1>Contact Us</h1>
                <br/>
                <?php
                $form = $this->form;
                $form->prepare();
                ?>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->form()->openTag($form); ?>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('email')); ?>
                            <?php echo $this->formElement($form->get('email')); ?>
                            <?php
                            echo $this->formElementErrors($form->get('email'));
                            echo "<br/>"
                            ?>
                        </div>   

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('subject')); ?>
                            <?php echo $this->formElement($form->get('subject')); ?>
                            <?php echo $this->formElementErrors($form->get('subject'));
                            ?>
                            <a href="../../../src/Application/Controller/IndexController.php"></a>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('body')); ?>
                            <?php echo $this->formElement($form->get('body')); ?>
                            <?php echo $this->formElementErrors($form->get('body'));
                            ?>


                            <?php echo $this->formElement($form->get('csrf')); ?>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('captcha')); ?>
                            <br>
                            <?php echo $this->formElement($form->get('captcha')); ?>
                            <br>
                            <?php echo $this->formElementErrors($form->get('captcha')); ?>
                            <br>
                            <p class="help-block">Enter the letters above as you see them.</p>
                        </div>

                        <div class="form-group">
                            <?php
                            echo $this->formElement($form->get('submit'));
                            echo "<br/>"
                            ?>
                        </div>
                        <?php echo $this->form()->closeTag(); ?> 
                    </div>
                </div>
                <br>
            </div>
        </div>
        <footer class="mainFooter">
            <br/>
            <p>Copyright by <a href="#">The Homestead Projects For Street Children</a> &COPY;2015.All rights reserved.
                <a href="http://www.givengain.com/cause/2949/"><img src='../../images/gg_secure_main_153_64.png'/></a></p>
            <br/>
        </footer>


        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.js"></script>
    </body>
</html>
