<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/custom.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.js')


        ;
        ?>

    </head>
    <body class="body"> 
        <header class="mainHeader">
            <div class='logo'>
                <div class="social">
                    <p class="follow"><b>Follow Us</b></p>
                    <a href="https://twitter.com/@homesteadpsc"><img src='../images/icons/twitter.png'/></a>
                    <a href="https://www.facebook.com/TheHomesteadProjectStreetChildren?fref=ts"><img src='../images/icons/facebook_2.png'/></a>
                    <br/><br/>
                    <p id="login"><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a> |
                        <a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a> </p>  
                </div>
                <img src="../images/logo3.png" class="logo-1"/>
            </div>
            <div class= "navbar navbar-default">
                <div class= "container">
                    <div class ="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class ="icon-bar"></span>
                            <span class ="icon-bar"></span>
                            <span class ="icon-bar"></span>
                            <span class ="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav  navbar-nav">
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('about/legal') ?>">Legal, NPO, PBO Status</a></li>
                                    <li><a href="http://issuu.com/paulvernonhooper/docs/the_homestead__projects_for_street_/1" target="_blank">Audited Financials  2014  </a></li>
                                    <li><a href="http://issuu.com/paulvernonhooper/docs/homestead_2014_final_low_res/1" target="_blank">Annual Report 2014</a></li>
                                    <li><a href="<?php echo $this->url('about/business') ?>">Business Canvas</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Gallery <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('gallery/photos') ?>">Photos</a></li>
                                    <li><a href="<?php echo $this->url('gallery/videos') ?>">Videos</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Donate <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('donate/myschool') ?>">My School</a></li>
                                    <li><a href="<?php echo $this->url('donate/youdonate') ?>">You Donate</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('volunteering') ?>"><?php echo $this->translate('Volunteering') ?></a></li>

                            <li class="dropdown active">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Our Projects <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('projects/intake') ?>">Intake Shelter</a></li>
                                    <li><a href="<?php echo $this->url('projects/children') ?>">Children Home</a></li>
                                    <li class="active"><a href="<?php echo $this->url('projects/outreach') ?>">Outreach Work</a></li>
                                    <li><a href="<?php echo $this->url('projects/prevention') ?>">Prevention and Early Intervention</a></li>

                                </ul>
                            </li>

                            <li><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact') ?></a></li>
                        </ul> 

                    </div>

                </div>
                <div class='c'></div>
            </div>

        </header>
        <div class='c'></div>
        <div class="wrapper">

            <div class="intake-wrapper">


                <div class="intake">
                    <div class="container-fluid">
                        <div class="row">
                            <div class='col-md-5'>
                                <h2>STREET OUTREACH</h2>
                                <p>The role of The Homestead Outreach worker  is to:</p>

                                <p>#-Identify, develop contact with and guide children living,
                                    working and begging on the street, as well as vulnerable 
                                    community children who seem to be drifting towards the street, 
                                    towards the appropriate Homestead programmes.</p>
                                <br/>
                                <p>#-Have ongoing contact with hardened children living on 
                                    the street, work with them in The Homestead Drop-in centres
                                    and coordinate a holistic response to try and unlock such children
                                    from the street and transition them into a stable, therapeutic environment.</p>
                                <br/>
                                <p>#-Collaborate with business, government departments, the police, 
                                    City improvement districts and others to help identify and monitor 
                                    children coming onto the street as well as the exploitation and support 
                                    that keeps children on the street and out of care.</p>
                                <br/>
                                <p>#-Ensure that children on the street are legally
                                    protected, that their families are identified and 
                                    worked with, and that where necessary a legal process 
                                    is begun to ensure such children are properly cared for and protected.</p>   
                            </div>
                            <div class='col-md-5'>
                                <img src='../images/homestead108.jpg' class='street'/>
                            </div>
                        </div>
                    </div>
                    <img src="../images/stop-begging.jpg" class="stop"/>
                    <br/><br/>
                </div>
                <footer class="mainFooter">
                    <br/>
                    <p>Copyright by <a href="#">The Homestead Projects For Street Children</a> &COPY;2015.All rights reserved.
                        <a href="http://www.givengain.com/cause/2949/"><img src='../../images/gg_secure_main_153_64.png'/></a></p>
                    <br/>
                </footer>

            </div>
            <script src="js/jquery.min.js"></script>
            <script src="js/bootstrap.js"></script>
    </body>
</html>