<h1>Registration</h1>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('register/default', array('controller' => 'registration', 'action' => 'index')));

$form->prepare();
?>
<div class="row">
    <div class="col-md-6">
        <?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('usr_name')) ; echo "<br/>";
echo $this->formRow($form->get('usr_email'));echo "<br/>";
echo $this->formRow($form->get('usr_password')); echo "<br/>";
echo $this->formRow($form->get('usr_password_confirm')); echo "<br/>";
echo $this->formRow($form->get('captcha')); echo "<br/>";
?>
<div class="form-group">
        <?php echo $this->formElement($form->get('submit')); echo "<br/>"?>
       </div>
     <?php echo $this->form()->closeTag(); ?> 
    </div>
</div>